apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
    type: NodePort
    selector:
      app: postgres
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      nodePort: 30032

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: NodePort
  selector:
   app: pgadmin
  ports:
   - port: 80
     nodePort: 30080