apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
    type: LoadBalancer
    selector:
      app: postgres
    ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    externalIPs:
    - 1.2.4.114

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: NodePort
  selector:
   app: pgadmin
  ports:
   - port: 80
     nodePort: 30080