"""profile + user

Revision ID: 0f7d72b6bcfc
Revises: 
Create Date: 2023-03-07 18:05:35.776411

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0f7d72b6bcfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=False),
    sa.Column('monthly_inhand_salary', sa.Float(), nullable=False),
    sa.Column('num_bank_accounts', sa.Float(), nullable=False),
    sa.Column('num_credit_card', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('num_of_loan', sa.Float(), nullable=False),
    sa.Column('num_of_delayed_payment', sa.Float(), nullable=False),
    sa.Column('changed_credit_limit', sa.Float(), nullable=False),
    sa.Column('num_credit_inquiries', sa.Float(), nullable=False),
    sa.Column('credit_mix', sa.String(), nullable=False),
    sa.Column('outstanding_debt', sa.Float(), nullable=False),
    sa.Column('credit_utilization_ratio', sa.Float(), nullable=False),
    sa.Column('credit_history_age', sa.Float(), nullable=False),
    sa.Column('payment_of_min_amount', sa.Float(), nullable=False),
    sa.Column('total_emi_per_month', sa.Float(), nullable=False),
    sa.Column('amount_invested_monthly', sa.Float(), nullable=False),
    sa.Column('payment_behaviour', sa.String(), nullable=False),
    sa.Column('monthly_balance', sa.Float(), nullable=False),
    sa.Column('times', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('hazard_score', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('risk_score', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('survival_score', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
