apiVersion: v1
kind: Service
metadata:
  name: infer-service
spec:
  selector:
    app: infer
  type: ClusterIP
  ports:
    - name: infer-model
      port: 3200
      targetPort: 3200
      protocol: TCP
    - name: infer-consumer
      port: 3220
      protocol: TCP
      targetPort: 3220