apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: finlytik-frontend
          image: realonbebeto/finlytik-frontend
          ports:
          - containerPort: 3600
          envFrom:
            - configMapRef:
                name: frontend-configmap
            - secretRef:
                name: frontend-secret