#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE mlflow;
	GRANT ALL PRIVILEGES ON DATABASE mlflow TO main;
	CREATE DATABASE optuna;
	GRANT ALL PRIVILEGES ON DATABASE optuna TO main;
EOSQL