apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  API_V1_STR: "/auth/v1"
  SECRET_KEY: "realonbebeto"
  ACCESS_TOKEN_EXPIRE_MINUTES: "10080"
  ALGORITHM: "HS256"
  PROJECT_NAME: "Finlytik"
  POSTGRES_HOST: host.minikube.internal
  POSTGRES_USER: main
  POSTGRES_DB: finlytik
  POSTGRES_PORT: "5432"
  SQLALCHEMY_DATABASE_URI: "postgresql://main:main123@host.minikube.internal:5432/finlytik"
  FIRST_SUPERUSER: "projobs254@gmail.com"
  USERS_OPEN_REGISTRATION: "True"


